### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by zhaohongqiangsoliva** [stevekm/IGV-snapshot-automator#13]
i install xvfb but it shown 
```
$ ./bin/Xvfb :0 -nolisten tcp -fp lib/X11/fonts/misc
(WW) Could not open RGB file "/usr/X11R6/lib/X11/rgb.txt"; will use built-in copy.
error opening security policy file /usr/X11R6/lib/X11/xserver/SecurityPolicy
_FontTransOpen: Unable to Parse address lib/X11/fonts/misc
Could not init font path element lib/X11/fonts/misc, removing from list!

Fatal server error:
could not open default font 'fixed'
```

**Comment by stevekm** [comment]
Hi @zhaohongqiangsoliva , I have never encountered this specific error but it sounds like your operating system might be missing some font packages. You might want to look up how to install missing fonts for your system. 

For reference, the included Singularity container file shows a known-working system configuration for Ubuntu 16.04; https://github.com/stevekm/IGV-snapshot-automator/blob/d32f17893c261f2eb2b671291bec168dcb5a62be/Singularity
