### ISSUE TITLE
an "hs_err_pid22398.log" produced 

### ISSUE THREAD

**Issue by chen318liang** [stevekm/IGV-snapshot-automator#15]
an "hs_err_pid22398.log" produced and the procedure is stopped. why and how to solve this problem. 

the content in this files is below:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb0d0181401, pid=22398, tid=22408
#
# JRE version: OpenJDK Runtime Environment (11.0.9+11) (build 11.0.9+11-Ubuntu-0ubuntu1.18.04.1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.9+11-Ubuntu-0ubuntu1.18.04.1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjimage.so+0x2401]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /software_users/chenliang/IGV-snapshot-automator/core.22398)
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
#

---------------  S U M M A R Y ------------

Command Line: -Xmx4000m bin/IGV_2.3.81/igv.jar -b IGV_Snapshots/IGV_snapshots.bat

Host:

**Comment by jrobinso** [comment]
Sorry that's really impossible for us to say.   This is a java crash.   You can submit a bug report to the link provided, as suggested in the message.

**Comment by chen318liang** [comment]
> Sorry that's really impossible for us to say. This is a java crash. You can submit a bug report to the link provided, as suggested in the message.

ok. thanks!
