### ISSUE TITLE
Load Bam files from URL

### ISSUE THREAD

**Issue by angelussong** [stevekm/IGV-snapshot-automator#22]
Hi, 
I am trying to take a few screenshots of specific variants from a very large bam files on a google bucket. I am wondering if there is a way of loading bam files from URL in IGV-snapshot-automator? 

I tried launching the igv.jar inside this folder and attempted to grant google access but it was blocked. I'm wondering if anybody has done this before and could you please help me troubleshoot it? 

Thank you!

**Comment by jrobinso** [comment]
@stevekm is the expert on the automator, but I think you are asking is there any way to load private BAMs from a google bucket, i.e. bams that require authentication.   I can't see how that would be possible in a headless environment with the current IGV release.  IGV popups the Google authentication page, then fetches the oAuth token returned to use with Google requests.   There's no way to supply or obtain this token from a headless setup.

What could work, but would require a modification to IGV, is to add a batch command to supply an oAuth token.   The user would have to obtain the token by other means.   I don't know what those means would be, or if it's possible, perhaps Google has some page to do this.   In any even if we want to pursue this open an issue at  igvteam/igv/issues to add the batch command and reference this issue.   Probably not a bad idea anyway.

**Comment by stevekm** [comment]
I am going to close this one since I do not thing its possible to implement.
