### ISSUE TITLE
count details of the region/locus of interest

### ISSUE THREAD

**Issue by umirshahi1** [stevekm/IGV-snapshot-automator#23]
hello. this automation is wonderful. could you add a line of code to show on the saved .png or output the count details of the region/locus of interest? Most of the time, all we need are in that window (strand bias, alt reads, ref reads, indel reads).  Thanks.

**Comment by stevekm** [comment]
Hi @umirshahi1 , thanks for your interest in the program. Unfortunately, `IGV-snapshot-automator` is simply a wrapper around the standard desktop IGV application's [batch script feature](https://software.broadinstitute.org/software/igv/batch), so it can only perform actions which are available via the batch script interface for IGV. From the sound of it, you might prefer to try the Broad team's official [`igv-reports`](https://github.com/igvteam/igv-reports) which creates HTML reports with the ability to embed variant / region data (e.g. from a vcf file) into your output.

**Comment by stevekm** [comment]
I am going to close this one for now, feel free to re-open and ping me if you find a way to implement this through the IGV batch script interface.
