### ISSUE TITLE
Trying to run on a Mac

### ISSUE THREAD

**Issue by afarahani951** [stevekm/IGV-snapshot-automator#25]
Hi, 

This is absolutely amazing thank you guys for making this! I am trying to run it on my MacOS and  getting stuck when it reaches the IGV command:

Running the IGV command...
/bin/sh: xvfb-run: command not found

Do you know if there is some alternative way to run the IGV command?

Thank you so much!

**Comment by stevekm** [comment]
My suggestion for Mac is to utilize the included Docker container / recipe and run it from there. `xvfb-run` is a helper script that is bundled with Linux X11 distros (I think), I would not expect it to be available on Mac and I am not sure what the equivalent might be (perhaps something to do with XQuartz?)

**Comment by stevekm** [comment]
Also worth noting that if you are on Mac then you already have a GUI available and you can simply use the `-nosnap` option to create your sample .bat batch script (or write the script yourself) and run it from IGV in batch mode yourself, so you do not actually need ` IGV-snapshot-automator` on Mac.
