### ISSUE TITLE
Instructions to get this working in cluster without X11

### ISSUE THREAD

**Issue by ManavalanG** [stevekm/IGV-snapshot-automator#9]
Figured I would share this here as this might help someone down the line. I use IGV in remote cluster where X11 is not available. I resolved this by using the instructions here - http://thedusseldorfer.blogspot.com/2013/09/remotely-plotting-with-igv-even-without.html. Note that this does not require sudo privileges.

Steps in brief:
1. Download `Xvfb.tgz` and `Xfnts.tgz` from `http://ftp.xfree86.org/pub/XFree86/4.8.0/binaries/`
2. Decompress them
3. Run this `./Xvfb :0 -nolisten tcp -fp /path/to/lib/X11/fonts/misc &`
4. Set `export DISPLAY=:0`
5. Now run IGV batch file: `/path/to/igv.sh --batch /path/to/batch/file`

I create IGV batch file using [IGV-snapshot-automator](https://github.com/stevekm/IGV-snapshot-automator), and with these batch files, I then create snapshots as described above. Hope this helps! If there is a better way to do this, or to get above `Xvfb` to work with `xvfb-run` and `xdpyinfo` without sudo privileges, please let me know.

**Comment by stevekm** [comment]
Thanks for this @ManavalanG 

I was looking into similar things recently, trying to get this to work on macOS where X11 runs through XQuartz, but it seemed rather complicated and I never did get it working. In particular, I found that `xvfb-run` is simply a wrapper script to launch and manage the X11 server window; I pulled a copy of it from my HPC system and saved it here:

https://github.com/stevekm/IGV-snapshot-nf/blob/master/bin/xvfb-run_Centos6

Notably, this script, and other versions of the same I found online, seem to use several tools that are not available on macOS, though you may fare better on a Linux OS.

**Comment by zhaohongqiangsoliva** [comment]
@ManavalanG  you can use anaconda install xvfb

**Comment by stevekm** [comment]
as a followup to this, I have included a Singularity container recipe which you can use, if your cluster has Singularity available. https://github.com/stevekm/IGV-snapshot-automator/blob/d32f17893c261f2eb2b671291bec168dcb5a62be/Singularity

**Comment by mewmewyahhey** [comment]
> @ManavalanG you can use anaconda install xvfb

I wonder which version of xvfb should I choose? I searched xvfb on the website of anaconda package and installed several of them, like xvfbwrapper, pytest-xvfb and xorg-x11-server-xvfb-cos7, but none of them has a command of "xvfb-run" and the tool didn't work.
